[project]
name = "daily-growth-steps"
version = "0.1.1"
description = "daily steps towards an excellent software engineer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.2",
]
